name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: "name of the artifact"
        required: false
        default: dist
        type: string
    outputs:
      result:
        description: "the result of the deployment operation"
        value: ${{ jobs.deploy.outputs.outcome }}
    # secrets:
    #   some-secret:
    #     required: true
        

jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: list files
        run: ls
      - name: Deploy website
        run: echo "deploying..."
      - name: set result output
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT